In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/input/IMDB-Movie-Data.csv')
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [3]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

---

### Challenge 1

In [4]:
def movie_votes(votes):
    if 0 < votes <= 999:
        return 1
    elif 1000 < votes <= 9999:
        return 2
    elif 10000 < votes <= 99999:
        return 3
    elif 100000 < votes <= 999999:
        return 4
    else:
        return 5

In [5]:
df['bins'] = df.apply(lambda x : movie_votes(x['Votes']), axis=1)

In [6]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4

---

### Challenge 2

In [7]:
# defino mi funcion

def revenue_minute(revenue, minute):
    return revenue / minute

In [8]:
revenue_minute(78, 8)

9.75

In [9]:
# Creo la nueva columna

df['revnue_minute'] = df.apply(lambda x : revenue_minute(x['Revenue (Millions)'], x['Runtime (Minutes)']), axis=1)

In [10]:
# Verifico resultado

df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins,revnue_minute
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4,2.753140
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4,1.019839
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4,1.180513
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4,2.642439

---
## Challenge 3

In [11]:
# We want to create a new ranking where we add 1 point if the genre is thriller but subtract 1 point if the genre is comedy.

In [12]:
# Defina la función
def rank_thriller (Genre, Rating):
    if 'Thriller' in Genre:
        return Rating + 1
    elif 'Comedy' in Genre:
        return Rating - 1
    else:
        return Rating

In [13]:
# Creo la nueva columna
df['Ranking_t'] = df.apply(lambda x : rank_thriller(x['Genre'], x['Rating']), axis=1)

In [14]:
# Verifico resultado
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins,revnue_minute,Ranking_t
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4,2.753140,8.1
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4,1.019839,7.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4,1.180513,8.3
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,6.2
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4,2.642439,6.2

---
### Challenge 4
Now the real stuff

We want to know if the sum of the ASCII value of every character of the movie title divided by the number of votes retrieve a prime number...remember, prime numbers are integers.

In [15]:
def is_prime(n):
    """
    Function to check if a number is prime.
    """
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

In [16]:
# combruebo que funcione
is_prime(11)

True

In [17]:
is_prime(15)

False

In [18]:
# defino la primera funcion que sumará los ascii de los títulos en una columna
df['sum_ascii'] = df['Title'].apply(lambda x: sum(ord(c) for c in x))

In [19]:
# defino la columna que dividira la suma de ascii entre los votos de películas
df['sum_div'] = df.apply(lambda x : revenue_minute(x['sum_ascii'], x['Votes']), axis=1)

In [20]:
# aplico la función con los resultados en otra columna
df['is_prime'] = df['sum_div'].apply(lambda x: is_prime(int(x)))

In [21]:
# compruebo resultado
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins,revnue_minute,Ranking_t,sum_ascii,sum_div,is_prime
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4,2.753140,8.1,2170,0.002866,False
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4,1.019839,7.0,1068,0.002198,False
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4,1.180513,8.3,524,0.003325,False
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,6.2,401,0.006623,False
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4,2.642439,6.2,1252,0.003180,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,3,NaN,6.2,1839,0.066667,False
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,3,0.186596,5.5,1298,0.017744,False
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,3,0.591939,6.2,1880,0.026592,False
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,2,NaN,4.6,1158,0.237246,False
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,3,0.225747,4.3,941,0.075674,False

In [22]:
'''
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

df['sum_ascii'] = df['title'].apply(lambda x: sum(ord(c) for c in x))
df['result'] = df['sum_ascii'] / df['votes']
df['is_prime'] = df['result'].apply(is_prime)
'''

"\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5)+1):\n        if n % i == 0:\n            return False\n    return True\n\ndf['sum_ascii'] = df['title'].apply(lambda x: sum(ord(c) for c in x))\ndf['result'] = df['sum_ascii'] / df['votes']\ndf['is_prime'] = df['result'].apply(is_prime)\n"

---
### Challenge 5. And finally some fantasy
Feel free to propose your own ranking based in aggregations of at least 3 columns of the dataset.

In [23]:
# valor del punto por beneficio
df['point_revenue'] = df['Revenue (Millions)'] / df['Rating']

In [24]:
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins,revnue_minute,Ranking_t,sum_ascii,sum_div,is_prime,point_revenue
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4,2.753140,8.1,2170,0.002866,False,41.127160
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4,1.019839,7.0,1068,0.002198,False,18.065714
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4,1.180513,8.3,524,0.003325,False,18.920548
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,6.2,401,0.006623,False,37.544444
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4,2.642439,6.2,1252,0.003180,False,52.422581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,3,NaN,6.2,1839,0.066667,False,NaN
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,3,0.186596,5.5,1298,0.017744,False,3.189091
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,3,0.591939,6.2,1880,0.026592,False,9.356452
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,2,NaN,4.6,1158,0.237246,False,NaN
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,3,0.225747,4.3,941,0.075674,False,3.705660

In [25]:
# añadir puntos por más votados
# creo la función
def add_rating(bins, rating):
    if bins == 1:
        return rating
    elif bins == 2:
        return rating +1
    elif bins == 3:
        return rating +2 
    elif bins == 4:
        return rating +3
    else:
        return rating +5

In [26]:
# añado la columna
df['rating_bins'] = df.apply(lambda x : add_rating(x['bins'], x['Rating']), axis=1)

In [27]:
# compruebo el resultado
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,bins,revnue_minute,Ranking_t,sum_ascii,sum_div,is_prime,point_revenue,rating_bins
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,4,2.753140,8.1,2170,0.002866,False,41.127160,11.1
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,4,1.019839,7.0,1068,0.002198,False,18.065714,10.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,4,1.180513,8.3,524,0.003325,False,18.920548,10.3
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,6.2,401,0.006623,False,37.544444,9.2
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,4,2.642439,6.2,1252,0.003180,False,52.422581,9.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,3,NaN,6.2,1839,0.066667,False,NaN,8.2
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,3,0.186596,5.5,1298,0.017744,False,3.189091,7.5
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,3,0.591939,6.2,1880,0.026592,False,9.356452,8.2
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,2,NaN,4.6,1158,0.237246,False,NaN,6.6
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,3,0.225747,4.3,941,0.075674,False,3.705660,7.3

In [29]:
# metascore entre rating para comprobar si estan equilibrados

# valor del punto por beneficio
df['equilibrio'] = df['Metascore'] / df['Rating']

In [30]:
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Metascore,bins,revnue_minute,Ranking_t,sum_ascii,sum_div,is_prime,point_revenue,rating_bins,equilibrio
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,...,76.0,4,2.753140,8.1,2170,0.002866,False,41.127160,11.1,9.382716
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,...,65.0,4,1.019839,7.0,1068,0.002198,False,18.065714,10.0,9.285714
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,...,62.0,4,1.180513,8.3,524,0.003325,False,18.920548,10.3,8.493151
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,...,59.0,3,2.502963,6.2,401,0.006623,False,37.544444,9.2,8.194444
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,...,40.0,4,2.642439,6.2,1252,0.003180,False,52.422581,9.2,6.451613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,...,45.0,3,NaN,6.2,1839,0.066667,False,NaN,8.2,7.258065
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,...,46.0,3,0.186596,5.5,1298,0.017744,False,3.189091,7.5,8.363636
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,...,50.0,3,0.591939,6.2,1880,0.026592,False,9.356452,8.2,8.064516
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,...,22.0,2,NaN,4.6,1158,0.237246,False,NaN,6.6,3.928571
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,...,11.0,3,0.225747,4.3,941,0.075674,False,3.705660,7.3,2.075472

---
### Challenge 6. Freaky bonus
We want to know which movies might have hidden paterns in their description. A way to know that is finding those movies which the sum of all numeric values of the string description hash (SHA256) are between their revenue and their number of votes.

In [ ]:
# no lo entiendo ni con chatGPT

In [32]:
import hashlib
import pandas as pd


# Define a function to extract all numeric values from a string
def extract_numeric_values(string):
    numeric_values = []
    for char in string:
        if char.isdigit():
            numeric_values.append(int(char))
    return numeric_values

# Calculate the SHA256 hash of the Description column for each movie
hashes = []
for desc in df["Description"]:
    hash_object = hashlib.sha256(desc.encode())
    hash_value = hash_object.hexdigest()
    hashes.append(hash_value)

# Extract all numeric values from the hash for each movie and sum them up
numeric_sums = []
for hash_value in hashes:
    numeric_values = extract_numeric_values(hash_value)
    numeric_sum = sum(numeric_values)
    numeric_sums.append(numeric_sum)

# Check if the sum of numeric values falls between the Revenue and Votes columns for each movie
for i in range(len(df)):
    if df.iloc[i]["Revenue (Millions)"] <= numeric_sums[i] <= df.iloc[i]["Votes"]:
        print(df.iloc[i]["Title"])
df

Prometheus
Split
The Great Wall
La La Land
The Lost City of Z
Passengers
Hidden Figures
Colossal
Hacksaw Ridge
Jason Bourne
Lion
Arrival
Gold
Manchester by the Sea
Independence Day: Resurgence
Bahubali: The Beginning
Dead Awake
Bad Moms
Assassin's Creed
Why Him?
Nocturnal Animals
X-Men: Apocalypse
Resident Evil: The Final Chapter
Interstellar
The Magnificent Seven
Sausage Party
Moonlight
The Founder
Lowriders
Miss Sloane
Star Trek Beyond
Underworld: Blood Wars
Mother's Day
John Wick
Silence
Don't Breathe
Me Before You
Their Finest
Sully
The Girl on the Train
Fifty Shades of Grey
The Prestige
Kingsman: The Secret Service
Patriots Day
Mad Max: Fury Road
Wakefield
Deepwater Horizon
Allied
A Monster Calls
Collateral Beauty
Inglourious Basterds
Ghostbusters
Captain Fantastic
The Wolf of Wall Street
Gone Girl
Live by Night
The Hateful Eight
The Accountant
Prisoners
Warcraft
War Dogs
The Nice Guys
Kimi no na wa
The Void
Personal Shopper
The Departed
Legend
Thor
The Man from U.N.C.L.E.
Hell or High Water
The Comedian
The Legend of Tarzan
Ex Machina
The Belko Experiment
12 Years a Slave
300
Office Christmas Party
The Neon Demon
Dangal
10 Cloverfield Lane
Miss Peregrine's Home for Peculiar Children
Mike and Dave Need Wedding Dates
Nerve
Mamma Mia!
The Revenant
Fences
Into the Woods
The Shallows
Whiplash
The Place Beyond the Pines
No Country for Old Men
The Great Gatsby
Shutter Island
Diary of a Wimpy Kid
The Big Short
Room
Django Unchained
Ah-ga-ssi
The Edge of Seventeen
Watchmen
Superbad
Inferno
The BFG
White Girl
Sicario
Aliens vs Predator - Requiem
Pacific Rim
Crazy, Stupid, Love.
Scott Pilgrim vs. the World
Hot Fuzz
Free Fire
Jack Reacher: Never Go Back
Casino Royale
Now You See Me 2
Woman in Gold
13 Hours
Nightcrawler
Kubo and the Two Strings
Her
Tomorrowland
Dawn of the Planet of the Apes
Tropic Thunder
The Conjuring 2
Ant-Man
Bridget Jones's Baby
The VVitch: A New-England Folktale
Forushande
Billy Lynn's Long Halftime Walk
Crimson Peak
Drive
Trainwreck
The Light Between Oceans
Spotlight
Morgan
Warrior
Into the Wild
The Imitation Game
Central Intelligence
Edge of Tomorrow
A Cure for Wellness
Snowden
Allegiant
X: First Class
Raw (II)
Paterson
Bridesmaids
San Andreas
Spring Breakers
Gods of Egypt
Monster Trucks
Kick-Ass
Hardcore Henry
It Follows
The Girl with the Dragon Tattoo
We're the Millers
American Honey
The Lobster
Predators
Pan's Labyrinth
A Kind of Murder
Apocalypto
The Huntsman: Winter's War
The Perks of Being a Wallflower
Jackie
The Disappointments Room
The Grand Budapest Hotel
The Host
Fury
Rock Dog
Terminator Genisys
Percy Jackson & the Olympians: The Lightning Thief
Les Misérables
Children of Men
20th Century Women
Spy
The Intouchables
Kynodontas
Straight Outta Compton
The Conjuring
Battleship
Lights Out
Norman: The Moderate Rise and Tragic Fall of a New York Fixer
Birdman or (The Unexpected Virtue of Ignorance)
Black Swan
Dear White People
Nymphomaniac: Vol. I
Teenage Mutant Ninja Turtles: Out of the Shadows
Knock Knock
Dirty Grandpa
Cloud Atlas
21 Jump Street
Sing Street
Oblivion
Zodiac
Everybody Wants Some!!
Now You See Me
The Danish Girl
Hercules
Sucker Punch
Keeping Up with the Joneses
Jupiter Ascending
Masterminds
Busanhaeng
Pitch Perfect
Neighbors 2: Sorority Rising
The Choice
Ice Age: Collision Course
The Devil Wears Prada
The Infiltrator
There Will Be Blood
The Equalizer
Lone Survivor
The Cabin in the Woods
The House Bunny
She's Out of My League
Inherent Vice
Alice Through the Looking Glass
The Fast and the Furious: Tokyo Drift
How to Be Single
La vie d'Adèle
The Babadook
Snowpiercer
The 5th Wave
The Visit
Step Up
Lovesong
RocknRolla
In Time
The Social Network
The Last Witch Hunter
Victor Frankenstein
A Street Cat Named Bob
Green Room
Blackhat
Storks
Dallas Buyers Club
Lincoln
Rush
Silver Linings Playbook
The Fault in Our Stars
Blended
Fast & Furious
Looper
White House Down
Pete's Dragon
The Three Musketeers
Stardust
American Hustle
Jennifer's Body
Midnight in Paris
Joy
The Dressmaker
Café Society
Insurgent
Seventh Son
The Theory of Everything
This Is the End
About Time
Step Brothers
Clown
Zombieland
Hail, Caesar!
Slumdog Millionaire
Ben-Hur
Sleight
The Maze Runner
Criminal
Wanted
Florence Foster Jenkins
Collide
Black Mass
Creed
Swiss Army Man
The Expendables 3
What We Do in the Shadows
Southpaw
Bridge of Spies
Everest
Pixels
Robin Hood
The Wolverine
John Carter
Keanu
The Gunman
Steve Jobs
Grown Ups 2
The Age of Adaline
The Incredible Hulk
Couples Retreat
Magic Mike
Bronson
The Best of Me
The Invitation
Zero Dark Thirty
Vacation
Taken
Mechanic: Resurrection
Tusk
Atonement
Shame
Hanna
The Babysitters
Pride and Prejudice and Zombies
300: Rise of an Empire
London Has Fallen
The Curious Case of Benjamin Button
Sin City: A Dame to Kill For
The Purge: Election Year
3 Idiots
Zoolander 2
Mission: Impossible - Ghost Protocol
Filth
The Longest Ride
The imposible
Kick-Ass 2
Brooklyn
Coraline
Blue Valentine
Silent Hill
Dredd
Hunt for the Wilderpeople
Carrie
Demolition
Pandorum
Olympus Has Fallen
I Am Number Four
Jagten
Get Hard
Just Go with It
Revolutionary Road
The Town
The Boy
Denial
Goosebumps
Salt
Enemy
District 9
The Other Guys
American Gangster
Marie Antoinette
Argo
Eddie the Eagle
The Lives of Others
Forgetting Sarah Marshall
The Giver
Triple 9
Angry Birds
Moonrise Kingdom
Hairspray
Safe Haven
Focus
Stake Land
The Book of Eli
Cloverfield
Point Break
Under the Skin
Super 8
Law Abiding Citizen
Maze Runner: The Scorch Trials
Carol
Youth
Savages
(500) Days of Summer
Movie 43
The Boy in the Striped Pyjamas
Shooter
The Happening
Bone Tomahawk
Easy A
Exodus: Gods and Kings
Chappie
Half of a Yellow Sun
Anthropoid
The Counselor
Viking
Trust
Birth of the Dragon
The Green Inferno
The Bourne Legacy
A Good Year
Friend Request
Lucy
A Quiet Passion
Need for Speed
Jack Reacher
The Do-Over
The Ghost Writer
Limitless
P.S. I Love You
Midnight Special
Don't Think Twice
Chuck
The Break-Up
Loving
Fantastic Four
The Boy Next Door
The Gift
Dracula Untold
In the Heart of the Sea
Idiocracy
The Expendables
Evil Dead
Sinister
Snow White and the Huntsman
Pan
Juno
A Hologram for the King
Money Monster
The Other Woman
Enchanted
The Intern
Little Miss Sunshine
Bleed for This
Clash of the Titans
The Finest Hours
Tron
All Good Things
Kickboxer: Vengeance
Sex Tape
What to Expect When You're Expecting
Moneyball
Ghost Rider
Unbroken
Immortals
Sunshine
Män som hatar kvinnor
Adoration
The Drop
She's the Man
Daddy's Home
Let Me In
Never Back Down
Grimsby
Moon
Megamind
Gangster Squad
Blood Father
Kung Fu Panda 3
The Rise of the Krays
Horrible Bosses
Mommy
Hellboy II: The Golden Army
Beautiful Creatures
Toni Erdmann
The Lovely Bones
The Assassination of Jesse James by the Coward Robert Ford
Don Jon
Bastille Day
2307: Winter's Dream
Mr. Right
The Secret Life of Walter Mitty
Dope
Underworld Awakening
Antichrist
Friday the 13th
Taken 3
Total Recall
Night at the Museum: Secret of the Tomb
Love & Other Drugs
The Interview
The Host
WALL·E
Knocked Up
Source Code
Lawless
Unfriended
American Reunion
The Pursuit of Happyness
Relatos salvajes
Frantz
Gran Torino
Burnt
Sleeping Beauty
Vampire Academy
Sweeney Todd: The Demon Barber of Fleet Street
Insidious
Popstar: Never Stop Never Stopping
Public Enemies
Boyhood
Eastern Promises
The Daughter
Pineapple Express
The First Time
Gone Baby Gone
The Heat
L'avenir
Anna Karenina
Regression
Ted 2
Pain & Gain
Blood Diamond
Child 44
The Hurt Locker
Green Lantern
The Mist
Escape Plan
Love, Rosie
The DUFF
The Age of Shadows
We Need to Talk About Kevin
Love & Friendship
The Mortal Instruments: City of Bones
Seven Pounds
The King's Speech
Hunger
Jumper
Tinker Tailor Soldier Spy
Resident Evil: Retribution
Dear Zindagi
Genius
Pompeii
Life of Pi
10 Years
I Origins
Live Free or Die Hard
Funny Games
RED
Australia
Faster
The Adjustment Bureau
The Hollars
The Judge
Closed Circuit
La tortue rouge
The Book of Life
Incendies
The Heartbreak Kid
Entourage
The Strangers
Noah
Neighbors
Nymphomaniac: Vol. II
Wild
Grown Ups
Blair Witch
Dark Shadows
Friends with Benefits
The Illusionist
The A-Team
The Guest
The Internship
Paul
Mr. Church
Hugo
The Blackcoat's Daughter
Body of Lies
Knight of Cups
The Mummy: Tomb of the Dragon Emperor
The Boss
Hands of Stone
El secreto de sus ojos
True Grit
We Are Your Friends
A Million Ways to Die in the West
Rules Don't Apply
Ouija: Origin of Evil
Percy Jackson: Sea of Monsters
Fracture
Oculus
In Bruges
This Means War
The Road
Conan the Barbarian
The Fighter
August Rush
Chef
Eye in the Sky
Eagle Eye
The Purge
PK
Ender's Game
Paper Towns
High-Rise
Quantum of Solace
Lady in the Water
The Fountain
31
The Man Who Knew Infinity
Unknown
Self/less
Mr. Brooks
Before We Go
Captain Phillips
Max Steel
Sisters
The Family
Zack and Miri Make a Porno
Ma vie de Courgette
Man on a Ledge
No Strings Attached
Rescue Dawn
A Walk Among the Tombstones
The World's End
Seven Psychopaths
Beowulf
Jack Ryan: Shadow Recruit
1408
The Gambler
Prince of Persia: The Sands of Time
The Spectacular Now
A United Kingdom
Turbo Kid
Mama
Orphan
To Rome with Love
Fantastic Mr. Fox
Inside Man
127 Hours
Annabelle
The Imaginarium of Doctor Parnassus
G.I. Joe: The Rise of Cobra
Christine
Shut In
Grindhouse
Disaster Movie
Rocky Balboa
Diary of a Wimpy Kid: Dog Days
Jane Eyre
Fool's Gold
The Dictator
The Loft
Bacalaureat
You Don't Mess with the Zohan
Horrible Bosses 2
A Bigger Splash
Melancholia
The Princess and the Frog
Unstoppable
Flight
La migliore offerta
42
21
Begin Again
Out of the Furnace
Vicky Cristina Barcelona
Barbershop: The Next Cut
Terminator Salvation
Freedom Writers
The Hills Have Eyes
Changeling
Remember Me
Alexander and the Terrible, Horrible, No Good, Very Bad Day
Locke
Horns
Indignation
The Stanford Prison Experiment
Diary of a Wimpy Kid: Rodrick Rules
Mission: Impossible III
En man som heter Ove
Dragonball Evolution
Red Dawn
One Day
Life as We Know It
28 Weeks Later
Warm Bodies
Blue Jasmine
G.I. Joe: Retaliation
Wrath of the Titans
Shin Gojira
Saving Mr. Banks
Transcendence
Rio
Equals
Babel
The Tree of Life
The Lucky One
Piranha 3D
50/50
This Is 40
Real Steel
Sex and the City
Rambo
Concussion
The Fall
The Ugly Truth
Bride Wars
Sleeping with Other People
Snakes on a Plane
What If
How to Train Your Dragon 2
RoboCop
Hello, My Name Is Doris
Ocean's Thirteen
Slither
Contagion
Il racconto dei racconti - Tale of Tales
Bridge to Terabithia
Coherence
Notorious
Goksung
The Expendables 2
Perfume: The Story of a Murderer
The Golden Compass
Centurion
Scouts Guide to the Zombie Apocalypse
17 Again
No Escape
Precious
The Sea of Trees
The Master
Footloose
If I Stay
The Love Witch
Talladega Nights: The Ballad of Ricky Bobby
The Human Centipede (First Sequence)
Super
Up in the Air
The Midnight Meat Train
What's Your Number?
Riddick
The Butler
King Cobra
After Earth
Kicks
Me and Earl and the Dying Girl
The Descendants
Sex and the City 2
The Kings of Summer
Death Race
That Awkward Moment
Legion
End of Watch
3 Days to Kill
Lucky Number Slevin
Trance
Into the Forest
The Other Boleyn Girl
I Spit on Your Grave
The Walk
The Lone Ranger
Texas Chainsaw 3D
Disturbia
Rock of Ages
Scream 4
Queen of Katwe
My Big Fat Greek Wedding 2
The Skin I Live In
Miracles from Heaven
Annie
Across the Universe
Let's Be Cops
Max
Your Highness
Final Destination 5
Endless Love
Selma
Underworld: Rise of the Lycans
Taare Zameen Par
Take Me Home Tonight
Resident Evil: Afterlife
Project X
Hostel: Part II
Step Up 2: The Streets
Nine Lives

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Metascore,bins,revnue_minute,Ranking_t,sum_ascii,sum_div,is_prime,point_revenue,rating_bins,equilibrio
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,...,76.0,4,2.753140,8.1,2170,0.002866,False,41.127160,11.1,9.382716
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,...,65.0,4,1.019839,7.0,1068,0.002198,False,18.065714,10.0,9.285714
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,...,62.0,4,1.180513,8.3,524,0.003325,False,18.920548,10.3,8.493151
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,...,59.0,3,2.502963,6.2,401,0.006623,False,37.544444,9.2,8.194444
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,...,40.0,4,2.642439,6.2,1252,0.003180,False,52.422581,9.2,6.451613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,...,45.0,3,NaN,6.2,1839,0.066667,False,NaN,8.2,7.258065
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,...,46.0,3,0.186596,5.5,1298,0.017744,False,3.189091,7.5,8.363636
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,...,50.0,3,0.591939,6.2,1880,0.026592,False,9.356452,8.2,8.064516
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,...,22.0,2,NaN,4.6,1158,0.237246,False,NaN,6.6,3.928571
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,...,11.0,3,0.225747,4.3,941,0.075674,False,3.705660,7.3,2.075472